[main_window]
x = 250
y = 100
width = 1600
height = 800

[sidebar]
width = 80
btn_size = 40
btn_x = 20
# setting
btn_1_y = 20
# export
btn_2_y = 80
# import
btn_3_y = 140
# exit
btn_4_y = 740

[header]
height = 60
padding = 10
# theme
btn_size = 40
btn_offset = 10

[footer]
height = 60
padding = 10

[main_menu]
margin = 40
scroll_spacing = 15
swipe_width = 272
swipe_radius = 45
swipe_spacing = 15
